/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BiomeApp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alvar
 */
public class AdministradorPanel extends javax.swing.JFrame {

    String cargo = "";

    /**
     * Creates new form Administrador
     */
    public AdministradorPanel(String cargo) {
        cargo = cargo;
        initComponents();
        this.setTitle("Administrador usuarios");
        this.setLocation(250, 50);
        this.setResizable(false);
        if (cargo.equals("medico")) {
            botom_medico.setEnabled(false);
            botom_enfermero.setEnabled(false);
            botom_biomedico.setEnabled(false);
            botom_equipos.setEnabled(false);
        }
        if (cargo.equals("biomedico")) {
            botom_medico.setEnabled(false);
            botom_enfermero.setEnabled(false);
            botom_biomedico.setEnabled(false);
        }

        if (cargo.equals("enfermero")) {
            botom_medico.setEnabled(false);
            botom_enfermero.setEnabled(false);
            botom_biomedico.setEnabled(false);
            botom_equipos.setEnabled(false);
        }
    }

    AdministradorPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botom_gestor = new javax.swing.JButton();
        botom_medico = new javax.swing.JButton();
        botom_biomedico = new javax.swing.JButton();
        botom_enfermero = new javax.swing.JButton();
        botom_equipos = new javax.swing.JButton();
        botom_paciente = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botom_gestor.setText("Gestor Usuarios");
        botom_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_gestorActionPerformed(evt);
            }
        });
        jPanel2.add(botom_gestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        botom_medico.setText("Registro Medico");
        botom_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_medicoActionPerformed(evt);
            }
        });
        jPanel2.add(botom_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        botom_biomedico.setText("Registro Biomedico");
        botom_biomedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_biomedicoActionPerformed(evt);
            }
        });
        jPanel2.add(botom_biomedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        botom_enfermero.setText("Registro Enfermero");
        botom_enfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_enfermeroActionPerformed(evt);
            }
        });
        jPanel2.add(botom_enfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        botom_equipos.setText("Registro Equipos");
        botom_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_equiposActionPerformed(evt);
            }
        });
        jPanel2.add(botom_equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        botom_paciente.setText("Registro Paciente");
        botom_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botom_pacienteActionPerformed(evt);
            }
        });
        jPanel2.add(botom_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrador");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botom_gestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_gestorActionPerformed

        new GestorUsuarios(cargo).setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_gestorActionPerformed

    private void botom_biomedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_biomedicoActionPerformed
        new RegistroBiomedicoPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_biomedicoActionPerformed

    private void botom_enfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_enfermeroActionPerformed
        new RegistroEnfermeroPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_enfermeroActionPerformed

    private void botom_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_equiposActionPerformed
        new RegistroEquipoPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_equiposActionPerformed

    private void botom_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_pacienteActionPerformed
        new RegistroPacientePanel(cargo).setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_pacienteActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void botom_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botom_medicoActionPerformed

        new RegistroMedicoPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_botom_medicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botom_biomedico;
    private javax.swing.JButton botom_enfermero;
    private javax.swing.JButton botom_equipos;
    private javax.swing.JButton botom_gestor;
    private javax.swing.JButton botom_medico;
    private javax.swing.JButton botom_paciente;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
